version: '3.8'

services:

  backend:
    build:
      context: ./dis-viz-backend
    ports:
      - "80:80"
    # Don't know why none of these work
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    # command: 
    #   - "uvicorn"
    #   - "app.main:app"
    #   - "--host"
    #   - "0.0.0.0"
    #   - "--port"
    #   - "80"
    # command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 80

  frontend:
    build:
      context: ./dis-viz-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    - PORT=3000
    - REACT_APP_BACKEND_PORT=80
    command: npm start